#!/bin/sh

CFG=$XDG_CONFIG_HOME/statusbar


while true
do

order=$(cat $CFG/order)
var=" "
while IFS= read -r f; do
    f="$CFG/scripts/$f"
    echo $f
    [[ -x "$f" ]] || continue
    out="  $($f)  "
    var="$out$var"
done <<< "$order"


xsetroot -name "$var"

sleep 15

done