#!/bin/sh

MYPATH=$(dirname "$0")

while true
do

order=$(cat "$MYPATH/order")
var=" "
while IFS= read -r f; do
    f="$MYPATH/scripts/$f"
    [[ -x "$f" ]] || continue
    out="  $($f)  "
    var="$out$var"
done <<< "$order"


xsetroot -name "$var"

sleep 10

done