#!/bin/sh

timestamp() { 
    date '+%s%N' --date="$1"
}

API_URL=https://api.aladhan.com/v1/calendarByCity

## ADDRESS ##
CITY=Jamestown
STATE=NC
COUNTRY=USA

OUTPUT_FILE="${CITY}_${STATE}_${COUNTRY}-prayers.json"

## GET DATA IF NOT ALREADY EXISTS ##
test -f $OUTPUT_FILE || curl -X GET -G $API_URL -d city=$CITY -d state=$STATE -d country=$COUNTRY -d annual=true -d iso8601=true > $OUTPUT_FILE

MONTH=$(date +'%-m')
DAY=$(date +'%-d')
DAY_INDEX=$(($DAY-1))

TIMES=$(cat $OUTPUT_FILE | jq -r ".data.\"${MONTH}\"[${DAY_INDEX}].timings | to_entries[] | .value")
for i in $TIMES
do
    [ "${i:0:1}" = '(' ] && continue
    
    now=$(timestamp "$date")
    salah=$(timestamp "$i")
    
    [ $now -le $salah ] && echo "$salah" && break

done